name: Setup Bun
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  setup-bun:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        bun-version:
          - latest
          - canary
          - "1.0.0"
          - "1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983"
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-bun
        name: Setup Bun
        uses: ./
        with:
          bun-version: ${{ matrix.bun-version }}
      - id: verify-bun
        name: Verify Bun
        run: |
          bun --version
